// Capoluoghi di provincia + principali comuni italiani sopra ~15.000 abitanti
export const ITALIAN_CITIES: string[] = [
  "Acireale",
  "Afragola",
  "Agrigento",
  "Albenga",
  "Alessandria",
  "Alghero",
  "Altamura",
  "Ancona",
  "Andria",
  "Aosta",
  "Aprilia",
  "Arezzo",
  "Arzano",
  "Ascoli Piceno",
  "Asti",
  "Avellino",
  "Aversa",
  "Avola",
  "Bagheria",
  "Bari",
  "Barletta",
  "Battipaglia",
  "Belluno",
  "Benevento",
  "Bergamo",
  "Biella",
  "Bologna",
  "Bolzano",
  "Brescia",
  "Brindisi",
  "Busto Arsizio",
  "Cagliari",
  "Caivano",
  "Caltanissetta",
  "Campobasso",
  "Canosa di Puglia",
  "Carbonia",
  "Carrara",
  "Casalnuovo di Napoli",
  "Caserta",
  "Casoria",
  "Castellammare di Stabia",
  "Catania",
  "Catanzaro",
  "Cerignola",
  "Cesena",
  "Chieti",
  "Cinisello Balsamo",
  "Civitavecchia",
  "Como",
  "Corato",
  "Cosenza",
  "Cremona",
  "Crotone",
  "Cuneo",
  "Empoli",
  "Enna",
  "Ercolano",
  "Faenza",
  "Fano",
  "Fasano",
  "Favara",
  "Fermo",
  "Ferrara",
  "Fidenza",
  "Firenze",
  "Foggia",
  "Forlì",
  "Formia",
  "Frosinone",
  "Gallarate",
  "Gela",
  "Genova",
  "Giugliano in Campania",
  "Gorizia",
  "Grosseto",
  "Guidonia Montecelio",
  "Iglesias",
  "Imola",
  "Imperia",
  "Isernia",
  "Ivrea",
  "Jesi",
  "L'Aquila",
  "La Spezia",
  "Ladispoli",
  "Lamezia Terme",
  "Lanciano",
  "Latina",
  "Lecce",
  "Lecco",
  "Legnano",
  "Licata",
  "Livorno",
  "Lodi",
  "Lucca",
  "Macerata",
  "Manfredonia",
  "Mantova",
  "Marano di Napoli",
  "Marsala",
  "Massa",
  "Matera",
  "Melito di Napoli",
  "Messina",
  "Milano",
  "Molfetta",
  "Monopoli",
  "Monreale",
  "Monza",
  "Napoli",
  "Nichelino",
  "Nocera Inferiore",
  "Nola",
  "Novara",
  "Nuoro",
  "Olbia",
  "Oristano",
  "Padova",
  "Paola",
  "Parma",
  "Pavia",
  "Perugia",
  "Pesaro",
  "Pescara",
  "Piacenza",
  "Pinerolo",
  "Pisa",
  "Pistoia",
  "Pordenone",
  "Portici",
  "Potenza",
  "Pozzuoli",
  "Prato",
  "Qualiano",
  "Quartu Sant'Elena",
  "Ragusa",
  "Ravenna",
  "Reggio Calabria",
  "Reggio Emilia",
  "Rho",
  "Rieti",
  "Rimini",
  "Roma",
  "Rovigo",
  "Salerno",
  "San Giorgio a Cremano",
  "San Severo",
  "Saronno",
  "Sassari",
  "Savona",
  "Scafati",
  "Sesto Fiorentino",
  "Sesto San Giovanni",
  "Settimo Torinese",
  "Siena",
  "Siracusa",
  "Sondrio",
  "Sorrento",
  "Taranto",
  "Teramo",
  "Terni",
  "Torino",
  "Torre Annunziata",
  "Torre del Greco",
  "Trani",
  "Trapani",
  "Trento",
  "Treviso",
  "Trieste",
  "Udine",
  "Varese",
  "Velletri",
  "Venezia",
  "Verbania",
  "Vercelli",
  "Verona",
  "Vibo Valentia",
  "Vicenza",
  "Vittoria",
  "Viterbo",
  "Voghera",
].sort((a, b) => a.localeCompare(b, "it"));
